"""tabela assinatura

Revision ID: 1b658bbbe4a3
Revises: 8da231da1ef5
Create Date: 2025-07-24 10:53:32.871525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b658bbbe4a3'
down_revision: Union[str, Sequence[str], None] = '8da231da1ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assinaturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assinaturas_id'), 'assinaturas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assinaturas_id'), table_name='assinaturas')
    op.drop_table('assinaturas')
    # ### end Alembic commands ###
